import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather, Open_Sans } from "next/font/google";
import TopLoader from "nextjs-toploader";
import "./globals.css";
import Header from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // normal + bold
  variable: "--merriweather",
  style: ["normal", "italic"],
  display: "swap",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600"], // regular + semi-bold
  variable: "--open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${merriweather.variable} ${openSans.variable} font-merriweather min-h-screen flex flex-col`}
      >
        <TopLoader showSpinner={false} color="#a06d06" height={1.9} />
        <Header />
        <main className="flex-1 pt-0">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
